import{describe,expect,it}from'vitest';
import{encodePayload,type Encoded}from'../protocol/codec';
import{V1,V2}from'../protocol/constants';
import{calibrationCells,payloadCells,type Cell}from'../protocol/geometry';
import{decodeImage}from'../decoder/decodeImage';
import jpeg from'jpeg-js';
import{project,solveHomography}from'../decoder/homography';

const sqrt3=Math.sqrt(3),hex=(h:string)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
function synthetic(e:Encoded,pitch=24){const q=3*pitch,side=Math.ceil(2*e.radius*pitch+2*q),data=new Uint8ClampedArray(side*side*4);data.fill(255);for(let i=3;i<data.length;i+=4)data[i]=255;const xy=(c:Cell)=>({x:q+(c.u+e.radius)*pitch,y:q+(c.v+e.radius*sqrt3/2)*pitch}),corners=[{q:-e.radius,r:0},{q:0,r:-e.radius},{q:e.radius,r:-e.radius},{q:e.radius,r:0},{q:0,r:e.radius},{q:-e.radius,r:e.radius}].map(c=>xy({q:c.q,r:c.r,u:c.q+c.r/2,v:c.r*sqrt3/2}));
 const put=(x:number,y:number,col:number[])=>{if(x<0||y<0||x>=side||y>=side)return;const i=4*(y*side+x);data[i]=col[0];data[i+1]=col[1];data[i+2]=col[2]};
 const seg=(p:{x:number;y:number},a:{x:number;y:number},b:{x:number;y:number})=>{const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)};
 for(let y=0;y<side;y++)for(let x=0;x<side;x++)if(corners.some((a,i)=>seg({x,y},a,corners[(i+1)%6])<pitch*.36))put(x,y,[17,19,24]);
 const draw=(c:Cell,s:number,mode:'dense'|'robust')=>{const p=xy(c),color=mode==='dense'?s>>1:s,marked=mode==='dense'&&(s&1),rad=e.version===2?pitch/sqrt3*.94:pitch*(1-V1.gapRatio)/2,mr=rad*(e.version===2?V2.markerRatio:V1.markerRatio),inside=(dx:number,dy:number,r:number)=>e.version===2?Math.abs(dx)<=sqrt3*r/2&&Math.abs(dy)<=r-Math.abs(dx)/sqrt3:Math.hypot(dx,dy)<=r;for(let y=Math.floor(p.y-rad);y<=p.y+rad;y++)for(let x=Math.floor(p.x-rad);x<=p.x+rad;x++){const dx=x-p.x,dy=y-p.y;if(inside(dx,dy,rad))put(x,y,hex(V1.colors[color]));if(marked&&inside(dx,dy,mr))put(x,y,color===0?hex(V1.markerLight):[16,18,22]);}};
 calibrationCells(e.radius).sort((a,b)=>Math.atan2(a.v,a.u)-Math.atan2(b.v,b.u)).forEach((c,i)=>draw(c,i%8,'dense'));payloadCells(e.radius).forEach((c,i)=>draw(c,e.symbols[i]??0,e.mode));if(e.version===2)for(let y=0;y<side;y++)for(let x=0;x<side;x++)if(corners.some((a,i)=>seg({x,y},a,corners[(i+1)%6])<pitch*.36))put(x,y,[17,19,24]);return{data,width:side,height:side,colorSpace:'srgb'} as ImageData;}
function mutate(im:ImageData,kind:string){const d=new Uint8ClampedArray(im.data),w=im.width,h=im.height;if(kind==='perspective'){const o=new Uint8ClampedArray(d.length);o.fill(255);const dst=[{x:18,y:8},{x:w-24,y:24},{x:w-8,y:h-22},{x:30,y:h-6}],src=[{x:0,y:0},{x:w-1,y:0},{x:w-1,y:h-1},{x:0,y:h-1}],map=solveHomography(dst,src);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=project(map,{x,y}),sx=Math.round(p.x),sy=Math.round(p.y);if(sx>=0&&sy>=0&&sx<w&&sy<h){const si=4*(sy*w+sx),di=4*(y*w+x);o.set(d.slice(si,si+4),di);}}return{data:o,width:w,height:h,colorSpace:'srgb'}as ImageData;}if(kind==='jpeg q55'){const out=jpeg.decode(jpeg.encode({data:Buffer.from(d),width:w,height:h},55).data,{useTArray:true});return{data:new Uint8ClampedArray(out.data),width:w,height:h,colorSpace:'srgb'}as ImageData;}if(kind==='rotate90'){const o=new Uint8ClampedArray(d.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const si=4*(y*w+x),di=4*(x*w+(h-1-y));o.set(d.slice(si,si+4),di);}return{data:o,width:h,height:w,colorSpace:'srgb'}as ImageData;}if(kind==='blur+white balance'){const o=new Uint8ClampedArray(d);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++)for(let c=0;c<3;c++){let s=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)s+=d[4*((y+yy)*w+x+xx)+c];const blurred=.55*d[4*(y*w+x)+c]+.45*s/9;o[4*(y*w+x)+c]=Math.min(255,blurred*([1.07,.94,.86][c])+7);o[4*(y*w+x)+3]=255;}return{data:o,width:w,height:h,colorSpace:'srgb'}as ImageData;}if(kind==='occlusion'){const cx=w*.62,cy=h*.57;for(let y=cy-12;y<cy+12;y++)for(let x=cx-12;x<cx+12;x++){const i=4*((y|0)*w+(x|0));d[i]=d[i+1]=d[i+2]=245;}return{data:d,width:w,height:h,colorSpace:'srgb'}as ImageData;}return im;}
function phoneScene(symbol:ImageData){const width=600,height=1000,data=new Uint8ClampedArray(width*height*4);data.fill(248);for(let i=3;i<data.length;i+=4)data[i]=255;const ox=140,oy=300;for(let y=0;y<symbol.height;y++)for(let x=0;x<symbol.width;x++){const source=4*(y*symbol.width+x),target=4*((y+oy)*width+x+ox);data.set(symbol.data.slice(source,source+4),target);}for(let y=0;y<height;y++)for(let x=0;x<14;x++){const i=4*(y*width+x);data[i]=data[i+1]=data[i+2]=8;}return{data,width,height,colorSpace:'srgb'}as ImageData;}
describe('image decoder',()=>{it.each(['clean','rotate90','perspective','jpeg q55','blur+white balance','occlusion'])('recovers robust honeycomb from %s raster',kind=>{const text='camera pipeline smoke test',e=encodePayload(text,'extreme','robust'),im=mutate(synthetic(e),kind),d=decodeImage(im);expect(d.text).toBe(text);expect(d.meanConfidence).toBeGreaterThan(.25)});});
describe('camera scenes',()=>{it('ignores a dark phone bezel around a smaller symbol',()=>{const text='continuous camera scan',image=phoneScene(synthetic(encodePayload(text,'high','robust'),10)),decoded=decodeImage(image);expect(decoded.text).toBe(text);});});
