import {useEffect,useRef,useState} from 'react';
import {Camera,Download,FileImage,ScanLine,Sparkles,Upload} from 'lucide-react';
import {encodePayload,type Encoded} from '../protocol/codec';
import {V1,type DensityMode,type EccProfile} from '../protocol/constants';
import {downloadCanvas,downloadSvg,renderCode,type Rendered} from '../encoder/render';
import {decodeImage,fileToImageData,type DecodeImageResult} from '../decoder/decodeImage';

export default function App(){const[tab,setTab]=useState<'encode'|'decode'>('encode');const[text,setText]=useState('Hello, HexGlyph! 你好，三角晶格。');const[profile,setProfile]=useState<EccProfile>('high');const[mode,setMode]=useState<DensityMode>('dense');const[cellSize,setCellSize]=useState(24);const[encoded,setEncoded]=useState<Encoded>();const[rendered,setRendered]=useState<Rendered>();const canvasHost=useRef<HTMLDivElement>(null);const[preview,setPreview]=useState<string>();const[result,setResult]=useState<DecodeImageResult>();const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[debug,setDebug]=useState(true);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream>();
 const generate=()=>{try{setError('');const e=encodePayload(text,profile,mode),r=renderCode(e,{cellSize,debug:false});setEncoded(e);setRendered(r);requestAnimationFrame(()=>{if(canvasHost.current){canvasHost.current.replaceChildren(r.canvas);}});}catch(e){setError(String(e instanceof Error?e.message:e));}};
 useEffect(generate,[]);
 const decodeBlob=async(file:Blob)=>{setBusy(true);setError('');try{const{x,canvas}=await fileToImageData(file);setPreview(canvas.toDataURL());setResult(decodeImage(x));}catch(e){setResult(undefined);setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const camera=async()=>{if(stream.current){stream.current.getTracks().forEach(t=>t.stop());stream.current=undefined;return;}try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1920}}});if(video.current){video.current.srcObject=stream.current;await video.current.play();}}catch(e){setError('摄像头不可用：'+e);}};
 const snap=async()=>{if(!video.current)return;const c=document.createElement('canvas');c.width=video.current.videoWidth;c.height=video.current.videoHeight;c.getContext('2d')!.drawImage(video.current,0,0);c.toBlob(b=>b&&decodeBlob(b),'image/jpeg',.92);};
 return <main><header><div className="brand"><span className="mark"><Sparkles size={20}/></span><div><h1>HexGlyph Lab</h1><p>Protocol V1 · triangular lattice visual code</p></div></div><nav><button className={tab==='encode'?'active':''} onClick={()=>setTab('encode')}>Encode</button><button className={tab==='decode'?'active':''} onClick={()=>setTab('decode')}>Decode</button></nav></header>
 {tab==='encode'?<section className="workspace"><aside className="panel controls"><label>UTF-8 payload<textarea value={text} onChange={e=>setText(e.target.value)} rows={7}/></label><div className="row"><label>ECC profile<select value={profile} onChange={e=>setProfile(e.target.value as EccProfile)}>{Object.entries(V1.profiles).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><label>Physical channel<select value={mode} onChange={e=>setMode(e.target.value as DensityMode)}><option value="dense">Dense · 8 states</option><option value="robust">Robust · 4 colors</option></select></label></div><label>Cell size <span>{cellSize}px</span><input type="range" min="12" max="48" value={cellSize} onChange={e=>setCellSize(+e.target.value)}/></label><button className="primary" onClick={generate}><Sparkles size={17}/> Generate</button>{error&&<p className="error">{error}</p>}</aside><article className="panel stage"><div className="eyebrow">LIVE SYMBOL</div><div className="canvas" ref={canvasHost}/>{encoded&&<div className="metrics"><Metric label="Payload" value={`${new TextEncoder().encode(text).length} B`}/><Metric label="Radius" value={`${encoded.radius}`}/><Metric label="Payload cells" value={`${encoded.capacity}`}/><Metric label="ECC" value={`${encoded.eccBytes} B`}/><Metric label="Density" value={`${mode==='dense'?3:2} bit/cell`}/></div>}<div className="actions"><button onClick={()=>rendered&&downloadCanvas(rendered.canvas)}><Download size={16}/> PNG</button><button onClick={()=>rendered&&downloadSvg(rendered.svg)}><Download size={16}/> SVG</button></div></article></section>:
 <section className="workspace"><aside className="panel controls"><label className="drop"><Upload/><strong>Upload image</strong><span>PNG, JPEG, WebP</span><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&decodeBlob(e.target.files[0])}/></label><div className="camera"><video ref={video} muted playsInline/><div className="row"><button onClick={camera}><Camera size={16}/> Camera</button><button onClick={snap}><ScanLine size={16}/> Scan frame</button></div></div><label className="check"><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/> Debug overlay</label>{busy&&<p className="status">正在定位六边形、校准颜色与执行 ECC…</p>}{error&&<p className="error">{error}</p>}</aside><article className="panel stage"><div className="eyebrow">DECODER</div>{preview?<div className="preview"><img src={preview}/>{debug&&result&&<svg viewBox={`0 0 ${result.readings.reduce((m,r)=>Math.max(m,r.point.x),1)} ${result.readings.reduce((m,r)=>Math.max(m,r.point.y),1)}`} className="overlay">{result.readings.map((r,i)=><circle key={i} cx={r.point.x} cy={r.point.y} r="2.5" fill={r.confidence<.45?'#ff4d5e':'#63e6be'} opacity=".75"/>)}<polygon points={result.corners.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#ffd43b" strokeWidth="3"/></svg>}</div>:<div className="empty"><FileImage size={48}/><h2>Drop a HexGlyph image</h2><p>检测边界后穷举旋转/镜像，由 V1 magic、RS 和 CRC 决定唯一方向。</p></div>}{result&&<div className="result"><span>Decoded payload</span><strong>{result.text}</strong><div className="metrics"><Metric label="Mode" value={result.mode}/><Metric label="Radius" value={`${result.radius}`}/><Metric label="ECC" value={result.profile}/><Metric label="Confidence" value={`${Math.round(result.meanConfidence*100)}%`}/></div></div>}</article></section>}
 <footer><span>Correctness first. Density second.</span><a href="https://github.com" target="_blank">Protocol notes</a></footer></main>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}

