import {useEffect,useMemo,useRef,useState} from 'react';
import {Camera,Download,FileImage,FileUp,Languages,ScanLine,Sparkles,Upload} from 'lucide-react';
import {encodeBytes,maxPayloadBytes,PayloadTooLargeError,type Encoded} from '../protocol/codec';
import {V1,type DensityMode,type EccProfile} from '../protocol/constants';
import {downloadCanvas,downloadSvg,renderCode,type Rendered} from '../encoder/render';
import {decodeImage,fileToImageData,type DecodeImageResult} from '../decoder/decodeImage';
import {canDecodeInWorker,startDecodeWorker,type DecodeJob,type DecodePhase} from '../decoder/workerClient';
import './enhancements.css';

type Lang='zh'|'en';
type InputKind='text'|'binary';
type BinaryInput={name:string;bytes:Uint8Array};

const copy={
 zh:{subtitle:'V2 协议 · 六边形蜂窝视觉码',encode:'编码',decode:'解码',language:'切换语言',payloadType:'数据类型',text:'文本',binary:'二进制',utf8Payload:'UTF-8 文本',filePayload:'二进制文件',chooseFile:'选择文件',fileHint:'支持任意文件内容，但受当前图形容量限制；文件名和 MIME 类型不会写入码中。',eccProfile:'纠错等级',channel:'物理通道',resolution:'单元分辨率',resolutionHint:'只影响导出像素；图形半径会按数据量自动选择。',generate:'生成',liveSymbol:'实时图形',payload:'数据',protocol:'协议',radius:'自动半径',outputSize:'输出尺寸',payloadCells:'数据单元',ecc:'纠错',density:'密度',capacity:'容量',autoSize:'V2 会拆分多个 RS 块，并按数据量自动选择更大的六边形半径。',upload:'上传 HexGlyph 图片',formats:'PNG、JPEG、WebP · 原图在后台解析',camera:'打开连续扫描',stopCamera:'停止扫描',debug:'Debug 覆盖层',loading:'正在后台读取原图…',processing:'正在后台定位六边形、校准颜色与执行 ECC…',scanning:(n:number)=>`正在连续扫描 · 已尝试 ${n} 帧`,cameraHint:'让六边形完整进入取景框并尽量占满画面；识别成功后会自动停止。',decoder:'解码器',dropTitle:'上传一张 HexGlyph 图片',dropText:'原图由后台线程解析；页面只显示受限尺寸的预览，不会被大图撑开。',decoded:'解码数据',binaryResult:'二进制数据',downloadBinary:'下载 .bin',mode:'模式',confidence:'置信度',footer:'正确性优先，密度其次。',source:'源码与协议',noFile:'请先选择一个文件。',cameraError:'摄像头不可用：',tooLarge:(n:number,max:number)=>`数据为 ${n} B；当前设置和最大六边形半径最多支持 ${max} B。可降低纠错等级或拆分数据。`},
 en:{subtitle:'Protocol V2 · hexagonal honeycomb visual code',encode:'Encode',decode:'Decode',language:'Switch language',payloadType:'Payload type',text:'Text',binary:'Binary',utf8Payload:'UTF-8 text',filePayload:'Binary file',chooseFile:'Choose file',fileHint:'Any file bytes are supported within the current symbol capacity. File name and MIME type are not stored.',eccProfile:'ECC profile',channel:'Physical channel',resolution:'Cell resolution',resolutionHint:'Only affects export pixels; symbol radius is selected automatically from payload size.',generate:'Generate',liveSymbol:'Live symbol',payload:'Payload',protocol:'Protocol',radius:'Auto radius',outputSize:'Output size',payloadCells:'Payload cells',ecc:'ECC',density:'Density',capacity:'Capacity',autoSize:'V2 splits data across RS blocks and selects a larger hexagonal radius automatically.',upload:'Upload a HexGlyph image',formats:'PNG, JPEG, WebP · decoded in background',camera:'Start continuous scan',stopCamera:'Stop scanning',debug:'Debug overlay',loading:'Reading the full image in the background…',processing:'Finding the hexagon, calibrating colors, and applying ECC in the background…',scanning:(n:number)=>`Scanning continuously · ${n} frames tried`,cameraHint:'Keep the whole hexagon in view and let it fill the frame. Scanning stops automatically on success.',decoder:'Decoder',dropTitle:'Upload a HexGlyph image',dropText:'The full image is decoded by a background worker; only a bounded preview is displayed here.',decoded:'Decoded payload',binaryResult:'Binary payload',downloadBinary:'Download .bin',mode:'Mode',confidence:'Confidence',footer:'Correctness first. Density second.',source:'Source & protocol',noFile:'Choose a file first.',cameraError:'Camera unavailable: ',tooLarge:(n:number,max:number)=>`Payload is ${n} B; these settings and the largest hexagonal radius allow ${max} B. Lower ECC or split the data.`}
} as const;

const eccNames:Record<Lang,Record<EccProfile,string>>={zh:{low:'低 · 12%',medium:'中 · 20%',high:'高 · 30%',extreme:'极高 · 40%'},en:{low:'Low · 12%',medium:'Medium · 20%',high:'High · 30%',extreme:'Extreme · 40%'}};

export default function App(){
 const[lang,setLang]=useState<Lang>(()=>localStorage.getItem('hexglyph-lang')==='en'?'en':'zh'),t=copy[lang];
 const[tab,setTab]=useState<'encode'|'decode'>('encode'),[inputKind,setInputKind]=useState<InputKind>('text');
 const[text,setText]=useState('Hello, HexGlyph! 你好，三角晶格。'),[binary,setBinary]=useState<BinaryInput>();
 const[profile,setProfile]=useState<EccProfile>('high'),[mode,setMode]=useState<DensityMode>('robust'),[cellSize,setCellSize]=useState(24);
 const[encoded,setEncoded]=useState<Encoded>(),[rendered,setRendered]=useState<Rendered>(),canvasHost=useRef<HTMLDivElement>(null);
 const[preview,setPreview]=useState<string>(),[result,setResult]=useState<DecodeImageResult>();
 const[error,setError]=useState(''),[busy,setBusy]=useState(false),[phase,setPhase]=useState<DecodePhase>('loading'),[debug,setDebug]=useState(true),[cameraActive,setCameraActive]=useState(false),[scanAttempts,setScanAttempts]=useState(0);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream>(),decodeJob=useRef<DecodeJob>(),previewUrl=useRef<string>();
 const payload=useMemo(()=>inputKind==='text'?new TextEncoder().encode(text):(binary?.bytes??new Uint8Array()),[inputKind,text,binary]),limit=maxPayloadBytes(profile,mode);

 useEffect(()=>{localStorage.setItem('hexglyph-lang',lang);document.documentElement.lang=lang==='zh'?'zh-CN':'en';},[lang]);
 useEffect(()=>()=>{decodeJob.current?.cancel();stream.current?.getTracks().forEach(track=>track.stop());if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);},[]);
 useEffect(()=>{if(cameraActive&&video.current&&stream.current){video.current.srcObject=stream.current;void video.current.play();}},[cameraActive]);
 const generate=()=>{try{setError('');if(inputKind==='binary'&&!binary)throw new Error(t.noFile);const e=encodeBytes(payload,profile,mode),r=renderCode(e,{cellSize,debug:false});setEncoded(e);setRendered(r);requestAnimationFrame(()=>canvasHost.current?.replaceChildren(r.canvas));}catch(e){setError(e instanceof PayloadTooLargeError?t.tooLarge(e.payloadBytes,e.maxBytes):(e instanceof Error?e.message:String(e)));}};
 useEffect(generate,[]);
 const chooseBinary=async(file?:File)=>{if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer());setBinary({name:file.name,bytes});setError(bytes.length>limit?t.tooLarge(bytes.length,limit):'');};
 const showPreview=(file:Blob)=>{if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);const url=URL.createObjectURL(file);previewUrl.current=url;setPreview(url);};
 const decodeBlob=(file:Blob,opt:{preview?:'now'|'success';silent?:boolean}={preview:'now'})=>{decodeJob.current?.cancel();if(opt.preview==='now')showPreview(file);setBusy(true);setPhase('loading');if(!opt.silent)setError('');if(opt.preview==='now')setResult(undefined);const job=canDecodeInWorker()?startDecodeWorker(file,setPhase):fallbackDecode(file);decodeJob.current=job;return job.promise.then(value=>{if(decodeJob.current!==job)return false;if(opt.preview==='success')showPreview(file);setResult(value);setError('');return true;}).catch(e=>{if(decodeJob.current!==job||e instanceof DOMException&&e.name==='AbortError')return false;if(!opt.silent)setError(e instanceof Error?e.message:String(e));return false;}).finally(()=>{if(decodeJob.current===job){decodeJob.current=undefined;setBusy(false);}});};
 const stopCamera=()=>{decodeJob.current?.cancel();stream.current?.getTracks().forEach(track=>track.stop());stream.current=undefined;if(video.current)video.current.srcObject=null;setCameraActive(false);};
 const camera=async()=>{if(cameraActive){stopCamera();return;}try{setError('');setResult(undefined);setScanAttempts(0);stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:2560},height:{ideal:1920}},audio:false});setCameraActive(true);}catch(e){setError(t.cameraError+(e instanceof Error?e.message:String(e)));}};
 const captureFrame=()=>new Promise<Blob|undefined>(resolve=>{const source=video.current;if(!source||source.readyState<2||!source.videoWidth){resolve(undefined);return;}const maxSide=1920,scale=Math.min(1,maxSide/Math.max(source.videoWidth,source.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(source.videoWidth*scale);canvas.height=Math.round(source.videoHeight*scale);canvas.getContext('2d')!.drawImage(source,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>resolve(blob??undefined),'image/jpeg',.97);});
 useEffect(()=>{if(!cameraActive)return;let cancelled=false,timer=0;const scan=async()=>{if(cancelled)return;const frame=await captureFrame();if(frame){setScanAttempts(n=>n+1);const found=await decodeBlob(frame,{preview:'success',silent:true});if(found){navigator.vibrate?.(120);stopCamera();return;}}if(!cancelled)timer=window.setTimeout(scan,300);};timer=window.setTimeout(scan,650);return()=>{cancelled=true;window.clearTimeout(timer);};},[cameraActive]);
 useEffect(()=>{if(tab!=='decode'&&cameraActive)stopCamera();},[tab,cameraActive]);
 const decodedText=result?readUtf8(result.bytes):undefined;
 return <main><header><div className="brand"><span className="mark"><Sparkles size={20}/></span><div><h1>HexGlyph Lab</h1><p>{t.subtitle}</p></div></div><div className="header-actions"><button className="lang-toggle" onClick={()=>setLang(lang==='zh'?'en':'zh')} aria-label={t.language}><Languages size={14}/><span className={lang==='zh'?'selected':''}>中</span><i>/</i><span className={lang==='en'?'selected':''}>EN</span></button><nav><button className={tab==='encode'?'active':''} onClick={()=>setTab('encode')}>{t.encode}</button><button className={tab==='decode'?'active':''} onClick={()=>setTab('decode')}>{t.decode}</button></nav></div></header>
 {tab==='encode'?<section className="workspace"><aside className="panel controls"><label>{t.payloadType}<span className="segmented"><button className={inputKind==='text'?'active':''} onClick={()=>setInputKind('text')}>{t.text}</button><button className={inputKind==='binary'?'active':''} onClick={()=>setInputKind('binary')}>{t.binary}</button></span></label>{inputKind==='text'?<label>{t.utf8Payload}<textarea value={text} onChange={e=>setText(e.target.value)} rows={7}/></label>:<label>{t.filePayload}<span className="file-picker"><FileUp size={18}/><strong>{binary?.name??t.chooseFile}</strong><small>{binary?`${binary.bytes.length} B`:t.fileHint}</small><input type="file" onChange={e=>chooseBinary(e.target.files?.[0])}/></span></label>}<div className="row"><label>{t.eccProfile}<select value={profile} onChange={e=>setProfile(e.target.value as EccProfile)}>{Object.keys(V1.profiles).map(k=><option key={k} value={k}>{eccNames[lang][k as EccProfile]}</option>)}</select></label><label>{t.channel}<select value={mode} onChange={e=>setMode(e.target.value as DensityMode)}><option value="dense">Dense · 8 states</option><option value="robust">Robust · 4 colors</option></select></label></div><label>{t.resolution} <span>{cellSize}px</span><input type="range" min="12" max="48" value={cellSize} onChange={e=>setCellSize(+e.target.value)}/><small>{t.resolutionHint}</small></label><div className="capacity"><span><b>{t.capacity}</b><strong>{payload.length} / {limit} B</strong></span><progress max={limit} value={Math.min(payload.length,limit)}/><small>{t.autoSize}</small></div><button className="primary" onClick={generate}><Sparkles size={17}/>{t.generate}</button>{error&&<p className="error">{error}</p>}</aside><article className="panel stage"><div className="eyebrow">{t.liveSymbol.toUpperCase()}</div><div className="canvas" ref={canvasHost}/>{encoded&&<div className="metrics"><Metric label={t.protocol} value={`V${encoded.version}`}/><Metric label={t.payload} value={`${payload.length} B`}/><Metric label={t.radius} value={`${encoded.radius}`}/><Metric label={t.outputSize} value={`${rendered?.side??0} px`}/><Metric label={t.payloadCells} value={`${encoded.capacity}`}/><Metric label={t.ecc} value={`${encoded.eccBytes} B`}/><Metric label={t.density} value={`${mode==='dense'?3:2} bit/cell`}/></div>}<div className="actions"><button onClick={()=>rendered&&downloadCanvas(rendered.canvas)}><Download size={16}/>PNG</button><button onClick={()=>rendered&&downloadSvg(rendered.svg)}><Download size={16}/>SVG</button></div></article></section>:
 <section className="workspace decode-workspace"><aside className="panel controls"><label className="drop"><Upload/><strong>{t.upload}</strong><span>{t.formats}</span><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file){if(cameraActive)stopCamera();void decodeBlob(file);}}}/></label><div className="camera"><div className={`camera-view ${cameraActive?'active scanning':''}`}>{cameraActive?<><video ref={video} muted playsInline/><span className="scan-frame" aria-hidden="true"/></>:<Camera size={34}/>}</div><small>{t.cameraHint}</small><button className={cameraActive?'scan-button active':''} onClick={camera}>{cameraActive?<ScanLine size={16}/>:<Camera size={16}/>} {cameraActive?t.stopCamera:t.camera}</button>{cameraActive&&<p className="scan-status"><i/>{t.scanning(scanAttempts)}</p>}</div><label className="check"><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/><span>{t.debug}</span></label>{busy&&!cameraActive&&<p className="status">{phase==='loading'?t.loading:t.processing}</p>}{error&&<p className="error">{error}</p>}</aside><article className="panel stage decode-stage"><div className="eyebrow">{t.decoder.toUpperCase()}</div>{preview?<div className="preview"><div className="preview-media"><img src={preview}/>{debug&&result&&<DebugOverlay result={result}/>}</div></div>:<div className="empty"><FileImage size={48}/><h2>{t.dropTitle}</h2><p>{t.dropText}</p></div>}{result&&<div className="result"><span>{t.decoded}</span>{decodedText!==undefined?<strong>{decodedText}</strong>:<div className="binary-result"><strong>{t.binaryResult} · {result.bytes.length} B</strong><button onClick={()=>downloadBytes(result.bytes)}><Download size={15}/>{t.downloadBinary}</button></div>}<div className="metrics"><Metric label={t.protocol} value={`V${result.version}`}/><Metric label={t.mode} value={result.mode}/><Metric label={t.radius} value={`${result.radius}`}/><Metric label={t.ecc} value={result.profile}/><Metric label={t.confidence} value={`${Math.round(result.meanConfidence*100)}%`}/></div></div>}</article></section>}
 <footer><span>{t.footer}</span><a href="https://github.com/simonheard/hexglyph" target="_blank" rel="noreferrer">{t.source}</a></footer></main>;
}

function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function DebugOverlay({result}:{result:DecodeImageResult}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const scale=Math.min(1,1600/result.imageWidth,1600/result.imageHeight),width=Math.max(1,Math.round(result.imageWidth*scale)),height=Math.max(1,Math.round(result.imageHeight*scale));canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');if(!context)return;context.scale(scale,scale);const radius=Math.max(2.5,result.imageWidth/500);for(const reading of result.readings){context.beginPath();context.arc(reading.point.x,reading.point.y,radius,0,Math.PI*2);context.fillStyle=reading.confidence<.45?'#ff4d5ebf':'#63e6bebf';context.fill();}context.beginPath();result.corners.forEach((point,index)=>index?context.lineTo(point.x,point.y):context.moveTo(point.x,point.y));context.closePath();context.strokeStyle='#ffd43b';context.lineWidth=Math.max(3,result.imageWidth/350);context.stroke();},[result]);return <canvas ref={ref} className="overlay" aria-hidden="true"/>;}
function fallbackDecode(file:Blob):DecodeJob{let cancelled=false;return{promise:fileToImageData(file).then(({x})=>{if(cancelled)throw new DOMException('Decode cancelled','AbortError');return decodeImage(x);}),cancel:()=>{cancelled=true;}};}
function readUtf8(bytes:Uint8Array){try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{return undefined;}}
function downloadBytes(bytes:Uint8Array){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));a.download='hexglyph-payload.bin';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
