import { V1,V2, type DensityMode } from '../protocol/constants';
import { calibrationCells, payloadCells, type Cell } from '../protocol/geometry';
import { decodeSymbols } from '../protocol/codec';
import { distance, mean, type RGB } from '../vision/color';
import {detectHexCandidates} from './detect';
import { project, solveHomography, type Pt } from './homography';

export type CellReading={point:Pt;symbol:number;confidence:number};
export type DecodeImageResult={text:string;bytes:Uint8Array;corners:Pt[];readings:CellReading[];radius:number;mode:DensityMode;profile:string;version:1|2;meanConfidence:number;imageWidth:number;imageHeight:number};
export type DecodeProgress={percent:number;stage:'loading'|'detecting'|'sampling'|'ecc';detail:string};
const SQRT3=Math.sqrt(3);
export async function fileToImageData(file:Blob){const bmp=await createImageBitmap(file),c=document.createElement('canvas');c.width=bmp.width;c.height=bmp.height;const x=c.getContext('2d')!;x.drawImage(bmp,0,0);return{x:x.getImageData(0,0,c.width,c.height),canvas:c};}
export function decodeImage(image:ImageData,onProgress?:(progress:DecodeProgress)=>void):DecodeImageResult{onProgress?.({percent:2,stage:'detecting',detail:'准备边界检测'});const candidates=detectHexCandidates(image,(fraction,detail)=>onProgress?.({percent:2+fraction*23,stage:'detecting',detail})),canonical=[{x:1,y:.5},{x:.25,y:1},{x:0,y:.5},{x:.75,y:0}],total=candidates.length*2*6*(V2.sizes.length+V1.sizes.length)*2;let last='',attempt=0;for(let candidateIndex=0;candidateIndex<candidates.length;candidateIndex++){const corners=candidates[candidateIndex];for(const version of [2,1] as const){const sizes=version===2?V2.sizes:V1.sizes;for(let mirror=0;mirror<2;mirror++)for(let shift=0;shift<6;shift++)for(const radius of sizes){const inner=inset(corners,radius),ordered=(i:number)=>inner[(mirror?shift-i+12:shift+i+6)%6],dst=[ordered(0),ordered(2),ordered(3),ordered(5)];let h:number[];try{h=solveHomography(canonical,dst);}catch{attempt+=2;continue;}for(const mode of ['robust','dense'] as DensityMode[]){attempt++;try{onProgress?.({percent:25+Math.floor(attempt/total*72),stage:'sampling',detail:`候选 ${candidateIndex+1}/${candidates.length} · V${version} · R${radius} · ${mode}`});const cal=calibrationCells(radius).sort((a,b)=>Math.atan2(a.v,a.u)-Math.atan2(b.v,b.u)),refs:RGB[][]=[[],[],[],[]];for(let i=0;i<cal.length;i++)refs[(i%8)>>1].push(sampleAnnulus(image,h,toNorm(cal[i],radius),radius));const centers=refs.map(mean),readings=payloadCells(radius).map(c=>classify(image,h,c,radius,mode,centers));onProgress?.({percent:25+Math.floor(attempt/total*72),stage:'ecc',detail:`校验 V${version} · R${radius} · ${mode}`});const decoded=decodeSymbols(readings.map(r=>r.symbol),radius,mode,[],version);onProgress?.({percent:100,stage:'ecc',detail:'ECC 与 CRC 校验成功'});return{text:decoded.text,bytes:decoded.bytes,corners,readings,radius,mode,profile:decoded.profile,version:decoded.version,meanConfidence:readings.reduce((s,r)=>s+r.confidence,0)/readings.length,imageWidth:image.width,imageHeight:image.height};}catch(e){last=e instanceof Error?e.message:String(e);}}}}}throw new Error(`无法解码：${last||'没有匹配的 V1/V2 几何、ECC 或 CRC'}`);}
function toNorm(c:Cell,r:number){return{x:.5+(c.u/(2*r)),y:.5+(c.v/(SQRT3*r))};}
function pixel(im:ImageData,p:Pt):RGB{const x=Math.max(0,Math.min(im.width-1,Math.round(p.x))),y=Math.max(0,Math.min(im.height-1,Math.round(p.y))),i=4*(y*im.width+x);return{r:im.data[i],g:im.data[i+1],b:im.data[i+2]};}
function medianColor(samples:RGB[]){const channel=(key:keyof RGB)=>{const values=samples.map(x=>x[key]).sort((a,b)=>a-b),middle=values.length>>1;return values.length%2?values[middle]:(values[middle-1]+values[middle])/2;};return{r:channel('r'),g:channel('g'),b:channel('b')};}
function sampleAnnulus(im:ImageData,h:number[],p:Pt,radius:number){const samples:RGB[]=[];for(const ring of [.15,.21])for(let i=0;i<8;i++){const a=(i+(ring>.15?.5:0))*Math.PI/4,d=ring/radius;samples.push(pixel(im,project(h,{x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d})));}return medianColor(samples);}
function sampleCenter(im:ImageData,h:number[],p:Pt,radius:number){const samples=[pixel(im,project(h,p))];for(let i=0;i<4;i++){const a=i*Math.PI/2,d=.045/radius;samples.push(pixel(im,project(h,{x:p.x+Math.cos(a)*d,y:p.y+Math.sin(a)*d})));}return medianColor(samples);}
function classify(im:ImageData,h:number[],c:Cell,radius:number,mode:DensityMode,centers:RGB[]):CellReading{const p=toNorm(c,radius),outer=sampleAnnulus(im,h,p,radius),ds=centers.map(x=>distance(outer,x)),order=[0,1,2,3].sort((a,b)=>ds[a]-ds[b]),center=mode==='dense'?sampleCenter(im,h,p,radius):pixel(im,project(h,p));const annLum=.2126*outer.r+.7152*outer.g+.0722*outer.b,cenLum=.2126*center.r+.7152*center.g+.0722*center.b,marked=Math.abs(cenLum-annLum)>42;const color=order[0],symbol=mode==='dense'?color*2+(marked?1:0):color,margin=(ds[order[1]]-ds[order[0]])/(ds[order[1]]+.01),shapeConf=Math.min(1,Math.abs(cenLum-annLum)/70),confidence=Math.max(0,Math.min(1,mode==='dense'?Math.min(margin*3,marked?shapeConf:1-shapeConf*.55):margin*3));return{point:project(h,p),symbol,confidence};}
function inset(points:Pt[],radius:number){const cx=points.reduce((s,p)=>s+p.x,0)/6,cy=points.reduce((s,p)=>s+p.y,0)/6,f=radius/(radius+.36);return points.map(p=>({x:cx+(p.x-cx)*f,y:cy+(p.y-cy)*f}));}
export function debugRead(image:ImageData,corners:Pt[],radius:number,mode:DensityMode,shift:number,mirror=0){const canonical=[{x:1,y:.5},{x:.25,y:1},{x:0,y:.5},{x:.75,y:0}],inner=inset(corners,radius),ordered=(i:number)=>inner[(mirror?shift-i+12:shift+i+6)%6],h=solveHomography(canonical,[ordered(0),ordered(2),ordered(3),ordered(5)]),cal=calibrationCells(radius).sort((a,b)=>Math.atan2(a.v,a.u)-Math.atan2(b.v,b.u)),refs:RGB[][]=[[],[],[],[]];for(let i=0;i<cal.length;i++)refs[(i%8)>>1].push(sampleAnnulus(image,h,toNorm(cal[i],radius),radius));const centers=refs.map(mean);return{centers,readings:payloadCells(radius).map(c=>classify(image,h,c,radius,mode,centers))};}
